app/models.py
from . import db
from . import login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class  blog:
    def __init__(self,id,title,overview,poster,vote_average,vote_count):
        self.id =id
        self.title = title
        self.overview = overview
        self.poster = "https://image.tmdb.org/t/p/w500/" + poster
        self.vote_average = vote_average
        self.vote_count = vote_count

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))
    reviews = db.relationship('Review',backref = 'user', lazy = "dynamic")

    @property
    def password(self):
            raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)
def __repr__(self):
    return f'User {self.username}'

class Role(db.Model):
     __tablename__ = 'roles'

     id = db.Column(db.Integer,primary_key = True)
     name = db.Column(db.String(255))
     users = db.relationship('User',backref = 'role',lazy="dynamic")
def __repr__(self):
        return f'User {self.name}'

class Review(db.Model):

    __tablename__ = 'reviews'

    id = db.Column(db.Integer,primary_key = True)
    movie_id = db.Column(db.Integer)
    movie_title = db.Column(db.String)
    image_path = db.Column(db.String)
    movie_review = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

    def save_review(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_reviews(cls,id):
        reviews = Review.query.filter_by(blog_id=id).all()
        return reviews

        

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class ReviewForm(FlaskForm):

    title = StringField('Review title',validators=[Required()])
    review = TextAreaField('Movie review', validators=[Required()])
    submit = SubmitField('Submit')

    class UpdateProfile(FlaskForm):
     bio = TextAreaField('Tell us about you.',validators = [Required()])
     submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # configure UploadSet
    configure_uploads(app,photos)

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

bootstrap = Bootstrap()

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from .forms import ReviewForm
from flask_login import login_required
from flask_login import UserMixin
from .. import db,photos
# Review = review.Review



#views
@main.route('/')
def index():

    title = 'blog'
    return render_template('index.html', title = title)

@main.route('/blog/review/new/<int:id>', methods = ['GET','POST'])
@login_required
def new_review(id):
    form = ReviewForm()
    blog = get_blog(id)
    if form.validate_on_submit():
        title = form.title.data
        review = form.review.data

        # update review instances
        new_review = Review(blog_id=blog.id,blog_title=title,image_path=blog.poster,blog_review=review,user=current_user)

        # save review method
        new_review.save_review()
        return redirect(url_for('.blog',id = blog.id ))

    title = f'{blog.title} review'
    return render_template('new_review.html',title = title, review_form=form, blog=blog)

# @main.route('/blog/<int:blog_id>')
# def blog(blog_id):

#     blog = blog_id
#     title = f'{blog.title}'
#     review = Review.get_reviews(blog_id)
#     return render_template('blog.html', id = blog_id,title = title,reviews = reviews)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)
    0
@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

# @main.route('/blog/review/new/<int:id>' )
# def new_review(id):
#     form = ReviewForm()
#     blog = get_blog(id)

#     if form.validate_on_submit():
#         title = form.title.data
#         review = form.review.data
#         new_review = Review(blog_id,title,blog.poster,review)
#         new_review.save_review()
#         return redirect(url_for('blog',id =blog_id))

#     title = f'{blog.title} review'
#     return render_template('new_review',title = title, ReviewForm = form, blog = blog) 

app/templates/base.html
{% extends 'bootstrap/base.html'%}

        {% include 'navbar.html' %}
        <hr>
        <br>
        {% block content%}

        {%endblock%}
    </body>
</html>

app/templates/blog.html
{%extends 'base.html'%}
<!-- Content block -->
{% block content %}
<div class="container-fluid">
    <!-- Poster background -->
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 posterPath" style="background: url({{blog.poster}}) no-repeat center center">
</div>

<div class = "row">
    <h1>reviews</h1>
        <hr>
        {%if reviews%}
           {{macros.displayReviews(reviews)}}
           {% else%}
           <h3 class="btn btn-success btn-lg text-center"> this blog has no reviews </h3>
</div>

<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 blog-details">
    <h3>{{ blog.title }}</h3>

    <p class="overview"> {{blog.overview }}</p>
    <p class="ratings"> <b> {{blog.vote_average }}</b> - <i>{{blog.vote_count}} votes </i> </p>
    <a class="ratings" href="/blog/review/new/{{blog.id}}"> Write a new review</a>

</div>
</div>

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}


<!-- Styles block -->

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
<!-- Content block -->
{% block content %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 70%;
      margin: auto;
  }
  </style>
</head>
<body>

<div class="container">
  <br>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

      <div class="item active">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-7_qoYxxuGwnWiB1peMCpiU_u8F6xj240uFGx4-iuywGKNVC6Ow" alt="" width="330" height="250">
        <div class="carousel-caption">
          <h3>Style</h3>
          <p>beauty is the key to confidence</p>
        </div>
      </div>

      <div class="item">
        <img src="http://blogrope.com/wp-content/uploads/2017/03/nyfwsat10.jpg" alt="" width="330" height="250">
        <div class="carousel-caption">
          <h3>fashion</h3>
          <p>The fashion of face art.</p>
        </div>
      </div>

      <div class="item">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGLyOLgkxXBHqTV0oCBhF22hZWA8YdqfRY2g84svHVhhe2v6FC" alt="fashion" width="460" height="250">
        <div class="carousel-caption">
          <h3>fashion</h3>
          <p>Beautiful thingz in the world.</p>
        </div>
      </div>

      <div class="item">
        <img src="http://www.chicous.com/wp-content/uploads/2014/05/Keiko-Lynns-Fashion-Blog-Parisian-Chic-770x514.jpg" alt="beauty" width="330" height="250">
        <div class="carousel-caption">
          <h3>beauty</h3>
          <p>Beautiful as a flowers .</p>
        </div>
      </div>

    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

</body>
</html>

<h1>hello word</h1>
{%endblock%}

app/templates/macros.html
{% macro displaymyblogList(myblog_list) %}

  {% endmacro %}

app/templates/navbar.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">MYBLOG</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">about</a></li>
      <li><a href="#">contact us:</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if current_user.is_authenticated %}
      <li>{{current_user.username}}</li>
      <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
      <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
      {% else %}
      <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
      {%endif%}
    </ul>
  </div>
</nav>

app/templates/new_review.html
{%extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
  <div class = "container-fluid">
      <div class = "col-md-8">
          <img src= "{{blog.poster}}" alt = "{{blog.title}}" class = "img-responsive">
      </div>
      <div class = "col-md-4">
      {{wtf.quick_form(review_form)}}
    </div>
  </div>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>
  {% endblock %}
  {% if user == current_user %}
      <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
  {% endif %}
  </div>


  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}

    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
      {% endif %}

  </div>
</div>

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
  {{wtf.quick_form(form)}}
{% endblock %}

app/templates/search.html
{% extends 'base.html'%}


{% block content %}
    <div class="container">

        <div class="row">

            <hr>
            <ul>

            </ul>

        </div>

    </div>
{% endblock %}